"""Write src/phaser/render/itemArt.ts from items.py (food, materials) and gear.py (equipment)."""
import json, os
from items import MEAT_PAL, LOG_PAL, MEAT_ICON, LOG_ICON, MEAT_DROP, LOG_DROP
from gear import GEAR
from backpack import backpack, PAL as BACKPACK_PAL
import ores
import craftart
import items2
import archery
def arr(rows, ind='    '): return "[\n" + "".join(f"{ind}{json.dumps(r.rstrip('.'))},\n" for r in rows) + ind[:-2] + "]"
def pal(p): return "{ " + ", ".join(f"{json.dumps(k)}: {json.dumps(v)}" for k, v in p.items()) + " }"
pals = {'meat': MEAT_PAL, 'cooked_meat': craftart.COOKED_PAL, 'log': LOG_PAL, 'iron_bar': craftart.IRON_BAR_PAL, 'gold_bar': craftart.GOLD_BAR_PAL, **{k: v[1] for k, v in ores.ICONS.items()}, **{k: v[1] for k, v in GEAR.items()}, 'pickaxe': ores.PICK_PAL, **{k: v[1] for k, v in items2.ICONS.items()}, **{k: v[1] for k, v in archery.ICONS.items()}}
icons = {'meat': MEAT_ICON, 'cooked_meat': craftart.COOKED_ICON, 'log': LOG_ICON, 'iron_bar': craftart.ingot_icon().rows(), 'gold_bar': craftart.ingot_icon().rows(), **{k: v[0].rows() for k, v in ores.ICONS.items()}, **{k: v[0].rows() for k, v in GEAR.items()}, 'pickaxe': ores.pickaxe().rows(), **{k: v[0].rows() for k, v in items2.ICONS.items()}, **{k: v[0].rows() for k, v in archery.ICONS.items()}}
# unique versions of common gear look like them (ItemDef.looks)
for k, base in {'edric_helm': 'iron_helm', 'elowen_amulet': 'vigour_amulet'}.items():
    pals[k] = pals[base]
    icons[k] = icons[base]
L = ["""import { PixelCanvas } from './pixelPainter';
import type { ItemId } from '../../data/items';

/**
 * Item art: 20×20 bag icons (like the action icons) for every item, and ground sprites for
 * items lying in the world: food and materials have their own, gear lies on the ground as
 * itself (its icon), so you see what it is before picking it up. Same HD treatment: 3–4
 * tones lit from the top-left and the hue-tinted outline. Generated by tools/heroes.
 */
""", "const PAL: Record<ItemId, Record<string, string>> = {"]
for k, p in pals.items(): L.append(f"  {k}: {pal(p)},")
L.append("};\n\nconst ICON: Record<ItemId, string[]> = {")
for k, r in icons.items(): L.append(f"  {k}: {arr(r)},")
L.append("};\n")
L.append(f"const DROP: Partial<Record<ItemId, string[]>> = {{\n  meat: {arr(MEAT_DROP)},\n  log: {arr(LOG_DROP)},\n" + "".join(f"  {k}: {arr(r)},\n" for k, (r, _) in ores.DROPS.items())
         + f"  cooked_meat: {arr(craftart.COOKED_DROP)},\n  iron_bar: {arr(craftart.INGOT_DROP)},\n  gold_bar: {arr(craftart.INGOT_DROP)},\n" + "};\n")
L.append(f"const BACKPACK_PAL = {pal(BACKPACK_PAL)};\nconst BACKPACK = {arr(backpack().rows(), '  ')};\n")
L.append(f"const HAMMER_PAL = {pal(craftart.HAMMER_PAL)};\nconst HAMMER = {arr(craftart.hammer().rows(), '  ')};\n")
L.append("""function paint(rows: string[], pal: Record<string, string>, k: number): HTMLCanvasElement {
  const w = Math.max(...rows.map(r => r.length));
  const p = new PixelCanvas(w, rows.length);
  rows.forEach((r, y) => [...r].forEach((ch, x) => ch !== '.' && pal[ch] && p.px(x, y, pal[ch])));
  return p.outline('auto', k).toCanvas();
}

/** Bag icon (22×22 with the outline). */
export function itemIcon(id: ItemId): HTMLCanvasElement {
  return paint(ICON[id], PAL[id], 0.3);
}

/** The inventory button: a leather backpack (22×22 with the outline). */
export function backpackIcon(): HTMLCanvasElement {
  return paint(BACKPACK, BACKPACK_PAL, 0.3);
}

/** The crafting button: a smith's hammer (22×22 with the outline). */
export function hammerIcon(): HTMLCanvasElement {
  return paint(HAMMER, HAMMER_PAL, 0.3);
}

/** Sprite for the item lying on the ground (HD scale): its own ground art, or the item itself. */
export function itemDrop(id: ItemId): HTMLCanvasElement {
  return paint(DROP[id] ?? ICON[id], PAL[id], 0.22);
}
""")
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), '../../src/phaser/render/itemArt.ts'), 'w').write("\n".join(L))


# ---------------------------------------------------------------- structureArt.ts
S = ["""import { PixelCanvas } from './pixelPainter';
import type { Pal } from './styles/silhouetteRound';

/**
 * Things you build: the campfire (3 flame frames) and the forge (2 frames of its glowing
 * mouth), at HD scale, plus chunky versions for the flat styles. Generated by tools/heroes
 * (craftart.py).
 */
"""]
S.append(f"const CAMP_PAL = {pal(craftart.CAMP_PAL)};")
S.append("const CAMPFIRE = [\n" + "".join("  " + arr(craftart.campfire(i).rows(), '    ') + ",\n" for i in range(3)) + "];\n")
S.append(f"const FORGE_PAL = {pal(craftart.FORGE_PAL)};")
S.append("const FORGE = [\n" + "".join("  " + arr(craftart.forge(i).rows(), '    ') + ",\n" for i in range(2)) + "];\n")
S.append("""function paint(rows: string[], pal: Record<string, string>): HTMLCanvasElement {
  const w = Math.max(...rows.map(r => r.length));
  const p = new PixelCanvas(w, rows.length);
  rows.forEach((r, y) => [...r].forEach((ch, x) => ch !== '.' && pal[ch] && p.px(x, y, pal[ch])));
  return p.outline('auto', 0.35).toCanvas();
}

/** HD campfire: three frames of flame over crossed logs in a ring of stones. */
export function campfireFrames(): HTMLCanvasElement[] {
  return CAMPFIRE.map(f => paint(f, CAMP_PAL));
}

/** HD forge: a stone furnace with a chimney and an anvil; two frames of its glowing mouth. */
export function forgeFrames(): HTMLCanvasElement[] {
  return FORGE.map(f => paint(f, FORGE_PAL));
}
""")
S.append("/** Chunky versions for the flat styles (drawn at 4×). */")
S.append("export const FLAT_CAMPFIRE: string[][] = " + json.dumps(craftart.CAMP4) + ";")
S.append("export const FLAT_FORGE: string[][] = " + json.dumps(craftart.FORGE4) + ";")
S.append("export const FLAT_PAL: Pal = " + json.dumps({**{k: v for k, v in craftart.CAMP_PAL.items() if k in 'YORrw'}, 's': '#9a9a96', 'M': '#a8a8a0', 'D': '#787870'}) + ";")
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), '../../src/phaser/render/structureArt.ts'), 'w').write("\n".join(S) + "\n")

# ---------------------------------------------------------------- npcArt.ts
import npcart
N = ["""import { PixelCanvas } from './pixelPainter';
import type { Pal } from './styles/silhouetteRound';
import type { NpcId } from '../../data/npcs';

/**
 * People in the world: Warden Aldric's HD idle (4 frames: breathing, beard and cloak sway),
 * and chunky versions for the flat styles. Generated by tools/heroes (npcart.py).
 */
"""]
N.append(f"const ALDRIC_PAL = {pal(npcart.PAL)};")
N.append("const ALDRIC = [\n" + "".join("  " + arr(npcart.aldric(f).rows(), '    ') + ",\n" for f in range(4)) + "];\n")
import villagers
N.append("/** The people of Millbrook (villagers.py): idle frames and palette each. */")
N.append("const PEOPLE: Record<string, { pal: Record<string, string>; frames: string[][] }> = {")
for vid in villagers.VILLAGERS:
    N.append(f"  {vid}: {{\n    pal: {pal(villagers.VILLAGERS[vid][1])},\n    frames: [\n" + "".join("      " + arr(fr.rows(), '        ') + ",\n" for fr in villagers.frames(vid)) + "    ],\n  },")
N.append("};\n")
N.append("""function paint(rows: string[], pal: Record<string, string>): HTMLCanvasElement {
  const w = Math.max(...rows.map(r => r.length));
  const p = new PixelCanvas(w, rows.length);
  rows.forEach((r, y) => [...r].forEach((ch, x) => ch !== '.' && pal[ch] && p.px(x, y, pal[ch])));
  return p.outline('auto', 0.22).toCanvas();
}

/** HD idle frames of an NPC (or of a wanderer such as the grey postman). */
export function npcFrames(id: NpcId | 'postman'): HTMLCanvasElement[] {
  if (id === 'aldric') return ALDRIC.map(f => paint(f, ALDRIC_PAL));
  const p = PEOPLE[id];
  return p.frames.map(f => paint(f, p.pal));
}
""")
N.append("/** Chunky versions for the flat styles (drawn at 4×). */")
N.append("export const FLAT_NPCS: Partial<Record<NpcId, string[][]>> = { aldric: " + json.dumps(npcart.FLAT) + " };")
N.append("export const FLAT_NPC_PAL: Pal = " + json.dumps(npcart.FLAT_PAL) + ";")
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), '../../src/phaser/render/npcArt.ts'), 'w').write("\n".join(N) + "\n")

# ---------------------------------------------------------------- uiIcons.ts
import menuicons
U = ["""import { PixelCanvas } from './pixelPainter';

/**
 * Menu bar, skill and talent icons: the skull (Execute), a sealed scroll (Quests), an iron
 * cog (Settings), a book (Controls), an eye, a flame, a heart and a star (Talents), and the
 * view button's map tile, turning block and camera. 20×20 with the HD outline. Generated by
 * tools/heroes (menuicons.py).
 */
"""]
for name, (g, p) in menuicons.ICONS.items():
    U.append(f"const {name.upper()}_PAL = {pal(p)};")
    U.append(f"const {name.upper()} = {arr(g.rows(), '  ')};\n")
U.append("""function paint(rows: string[], pal: Record<string, string>): HTMLCanvasElement {
  const w = Math.max(...rows.map(r => r.length));
  const p = new PixelCanvas(w, rows.length);
  rows.forEach((r, y) => [...r].forEach((ch, x) => ch !== '.' && pal[ch] && p.px(x, y, pal[ch])));
  return p.outline('auto', 0.3).toCanvas();
}

""")
for name in menuicons.ICONS:
    U.append(f"export const {name}Icon = (): HTMLCanvasElement => paint({name.upper()}, {name.upper()}_PAL);")
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), '../../src/phaser/render/uiIcons.ts'), 'w').write("\n".join(U) + "\n")

# ---------------------------------------------------------------- skillIcons.ts
import skillicons
K = ["""import { PixelCanvas } from './pixelPainter';

/**
 * Skill icons for the action bar, spellbook and talents (20×20, 22×22 with the outline): one
 * object plus its effect, lit from the top-left. Digits and * + are glow: drawn over the
 * outline, never outlined. Generated by tools/heroes (skillicons.py).
 */
"""]
K.append(f"const PAL: Record<string, string> = {pal(skillicons.ALL)};")
K.append("const GLOW = " + json.dumps(''.join(skillicons.GLOW)) + ";\n")
for name, f in skillicons.ICONS.items():
    K.append(f"const {name.upper()} = {arr(f().rows(), '  ')};\n")
K.append("""function paint(rows: string[]): HTMLCanvasElement {
  const w = Math.max(...rows.map(r => r.length));
  const p = new PixelCanvas(w, rows.length);
  const each = (glow: boolean) =>
    rows.forEach((r, y) => [...r].forEach((ch, x) => ch !== '.' && GLOW.includes(ch) === glow && p.px(x, y, PAL[ch])));
  each(false);
  p.outline('auto', 0.3);
  each(true);
  return p.toCanvas();
}

export const SKILL_ICONS: Record<string, () => HTMLCanvasElement> = {""")
for name in skillicons.ICONS:
    K.append(f"  {name}: () => paint({name.upper()}),")
K.append("};")
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), '../../src/phaser/render/skillIcons.ts'), 'w').write("\n".join(K) + "\n")

# ---------------------------------------------------------------- objectArt.ts
import objects
O = ["""import { PixelCanvas } from './pixelPainter';

/**
 * Things you can use in the world (data/regions objects): a page lying in the grass (two
 * frames: a glint so it can be spotted), a notice board and a chest. HD scale, outlined
 * like the campfire. Generated by tools/heroes (objects.py).
 */
"""]
O.append(f"const PAL: Record<string, string> = {pal(objects.PAL)};")
for name, frames in objects.OBJECTS.items():
    O.append(f"const {name.upper()} = [\n" + "".join("  " + arr(g.rows(), '    ') + ",\n" for g in frames) + "];\n")
O.append("""function paint(rows: string[]): HTMLCanvasElement {
  const w = Math.max(...rows.map(r => r.length));
  const p = new PixelCanvas(w, rows.length);
  rows.forEach((r, y) => [...r].forEach((ch, x) => ch !== '.' && PAL[ch] && p.px(x, y, PAL[ch])));
  return p.outline('auto', 0.35).toCanvas();
}

export const OBJECT_FRAMES: Record<string, () => HTMLCanvasElement[]> = {""")
for name in objects.OBJECTS:
    O.append(f"  {name}: () => {name.upper()}.map(paint),")
O.append("};")
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), '../../src/phaser/render/objectArt.ts'), 'w').write("\n".join(O) + "\n")

# ---------------------------------------------------------------- creatureArt.ts
import creatures
C = ["""import { PixelCanvas } from './pixelPainter';

/**
 * Act I creatures at the HD scale: the bone hound (a two-frame trot) and the Bell-Ringer
 * (the boss of the Millbrook bell tower). Generated by tools/heroes (creatures.py).
 */

const ART: Record<string, { pal: Record<string, string>; frames: string[][] }> = {"""]
for cid, (make, cpal) in creatures.CREATURES.items():
    C.append(f"  {cid}: {{\n    pal: {pal(cpal)},\n    frames: [\n" + "".join("      " + arr(fr, '        ') + ",\n" for fr in make()) + "    ],\n  },")
C.append("""};

function paint(rows: string[], pal: Record<string, string>): HTMLCanvasElement {
  const w = Math.max(...rows.map(r => r.length));
  const p = new PixelCanvas(w, rows.length);
  rows.forEach((r, y) => [...r].forEach((ch, x) => ch !== '.' && pal[ch] && p.px(x, y, pal[ch])));
  return p.outline('auto', 0.22).toCanvas();
}

/** Frames of one of the Act I creatures ('bonehound', 'bellringer'). */
export function creatureFrames(id: 'bonehound' | 'bellringer'): HTMLCanvasElement[] {
  const a = ART[id];
  return a.frames.map(f => paint(f, a.pal));
}""")
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), '../../src/phaser/render/creatureArt.ts'), 'w').write("\n".join(C) + "\n")
