import { PixelCanvas } from './pixelPainter';

/**
 * Things you can use in the world (data/regions objects): a page lying in the grass (two
 * frames: a glint so it can be spotted), a notice board and a chest. HD scale, outlined
 * like the campfire. Generated by tools/heroes (objects.py).
 */

const PAL: Record<string, string> = { "P": "#f6e6c0", "p": "#dcc08a", "q": "#a8885a", "l": "#6a4a2a", "W": "#c48e5a", "w": "#8e5c32", "x": "#5c3a1c", "k": "#3a2410", "I": "#c4cedc", "i": "#7e8aa0", "j": "#4c5468", "G": "#ffe07a", "g": "#c8901e", "R": "#d8483a", "r": "#8e2a20", "Y": "#ffffff", "T": "#9a8eaa", "t": "#4e4258", "u": "#2e2632", "v": "#1d1b22", "a": "#8a867c", "e": "#5a4a3a" };
const PAGE = [
  [
    ".....pPPPP",
    "...pPPPPPPPP",
    ".pPPlllPPPPPPp",
    "pPPPPPPllPPPPpqq",
    ".qPPPllllPPPPPPq",
    "..qPPPPPPllPPPq",
    "...qqPPPPPPPPq",
    ".....qqqPPPpq",
    "........qqq",
    "",
  ],
  [
    "....YpPPPP",
    "...YPPPPPPPP",
    ".pPPlllPPPPPPpY",
    "pPPPPPPllPPPPpqq",
    ".qPPPllllPPPPPPq",
    "..qPPPPPPllPPPq",
    "...qqPPPPPPPPq",
    ".....qqqPPPpq",
    "........qqq",
    "",
  ],
];

const BOARD = [
  [
    "...........xx",
    ".........xxWWxx",
    ".......xxWWWWWWxx",
    ".....xxWWWWWWWWWWxx",
    "...xxwWWWWWWWWWWWWwxx",
    ".xxwwwwwwwwwwwwwwwwwwxx",
    ".kkkkkkkkkkkkkkkkkkkkkk",
    "..xWWWWWWWWWWWWWkWWWWWx",
    "..xWWWkWWWWWpPPPPPPPpWx",
    "..xWpPPPPPpWpPPPPPPPpWx",
    "..xwpPPPPPpwplllllllpwx",
    "..xWpllllPpWpPPPPPPPpWx",
    "..xWpPPPPPpWplllllllpWx",
    "..xWpllllPpWpPPPPPPPpWx",
    "..xWpPPPPPpWpllllPPPpWx",
    "..xwpPPllPpwpPPRRRPPpwx",
    "..xWqqqqqqqWpPPRrRPPpWx",
    "..xWWWWWWWWWpPPPrPPPpWx",
    "..xWWWWWWWWWqqqqqqqqqWx",
    "..xWWWWWWWWWWWWWWWWWWWx",
    "..xwwwwwwwwwwwwwwwwwwwx",
    "..kxxxxxxxxxxxxxxxxxxxk",
    "....Ww............Ww",
    "....Ww............Ww",
    "....Ww............Ww",
    "....Ww............Ww",
    "....Ww............Ww",
    "....Ww............Ww",
    "....Ww............Ww",
    "....Ww............Ww",
    "...xxxx..........xxxx",
  ],
];

const CHEST = [
  [
    "...xxxxxxxxxxxxxx",
    ".xWWWWWWWWWWWWWWWWx",
    ".xWWWWWWWWWWWWWWWwx",
    ".xwwwwwwwwwwwwwwwwx",
    ".jIIiiiijGGjiiiiiIj",
    ".jIIiiiijGgjiiiiiij",
    ".xwiwwwwwggwwwwwiwx",
    ".xWiWWWWWWWWWWWWiwx",
    ".xWiWWWWWWWWWWWWiwx",
    ".xwiwwwwwwwwwwwwiwx",
    ".xWiWWWWWWWWWWWWiwx",
    ".xWiWWWWWWWWWWWWiwx",
    ".xwiwwwwwwwwwwwwiwx",
    ".xxxxxxxxxxxxxxxxxx",
    "..kkkkkkkkkkkkkkkk",
  ],
];

const THORN = [
  [
    ".......T",
    ".......t......T",
    "......tu......t",
    "..T...tu.....tu",
    "..tu..tuT...tu",
    "...tu.tu...tu...T",
    "...tuutu...tu..tu",
    "....tuu.u.tuu.tu",
    "....tuu..tuu..tu",
    "...u.tu.tuu..tuu",
    "....utuutuuutuu",
    ".....tuuuuuuuu.u",
    "......tuuuuuu",
    "....uuvuvvuvuu",
    "..eaavvvvvvvvaae",
    ".eaeaaeaaaaeaeaee",
    "..eeaeeeaaeeeaee",
    "....eeeeeeeeee",
  ],
];

const LETTER = [
  [
    "......pPPPq",
    "....pPPPPPPPq",
    "..pPPlPPPPPPPPq",
    "pPPPPPllPPPPPPPPq",
    ".qPPPPPPlRRPPPPPPq",
    "..qPPPPPRrrRPPPq",
    "...qPPPPPRRPPPq",
    "....qqPPPPPPq",
    "......qqqqq",
  ],
  [
    "......YPPPq",
    "....pYPPPPPPq",
    "..pPPlPPPPPPPPq",
    "pPPPPPllPPPPPPPPY",
    ".qPPPPPPlRRPPPPPPq",
    "..qPPPPPRrrRPPPq",
    "...qPPPPPRRPPPq",
    "....qqPPPPPPq",
    "......qqqqq",
  ],
];

function paint(rows: string[]): HTMLCanvasElement {
  const w = Math.max(...rows.map(r => r.length));
  const p = new PixelCanvas(w, rows.length);
  rows.forEach((r, y) => [...r].forEach((ch, x) => ch !== '.' && PAL[ch] && p.px(x, y, PAL[ch])));
  return p.outline('auto', 0.35).toCanvas();
}

export const OBJECT_FRAMES: Record<string, () => HTMLCanvasElement[]> = {
  page: () => PAGE.map(paint),
  board: () => BOARD.map(paint),
  chest: () => CHEST.map(paint),
  thorn: () => THORN.map(paint),
  letter: () => LETTER.map(paint),
};
