import { PixelCanvas } from './pixelPainter';
import type { Pal } from './styles/silhouetteRound';

/**
 * Things you build: the campfire (3 flame frames) and the forge (2 frames of its glowing
 * mouth), at HD scale, plus chunky versions for the flat styles. Generated by tools/heroes
 * (craftart.py).
 */

const CAMP_PAL = { "S": "#d4d8de", "s": "#a8aeb8", "k": "#6e7480", "W": "#b07844", "w": "#7a4e28", "c": "#f0d49a", "e": "#ff8a3a", "E": "#c8401e", "Y": "#fff6b0", "O": "#ffb03c", "R": "#ff6a2a", "r": "#c8361c" };
const CAMPFIRE = [
  [
    "",
    "",
    "",
    "",
    "",
    "...........R",
    "...........RR",
    "..........RRR",
    "..........ROR.R",
    ".........RROORR",
    ".........ROOOOR",
    "........RROYYOR",
    "........ROOYYYOR",
    "........ROYYYYOR",
    ".......RROYYYYOSs",
    ".....Ss.ROOYYOOsk..Ss",
    "....sk...rRRRRr....sk",
    ".Ss....WWw....wWW....Ss",
    "Ssk..cWWww....wwWWc..sk",
    ".sk..WwwwEeEEe.wwwW",
    "....Ss...EeE.eE....Ss",
    "...skk...Sss..Ss..skk",
    ".........kkk..skk",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "............R",
    "........R..RR",
    "........R.RRR",
    "........RRROR",
    ".........ROOOR",
    "........RROOOOR",
    "........ROOYYOR",
    ".......RROYYYOOR",
    "........ROYYYYOR",
    ".......RROYYYYOSs",
    ".....Ss.ROOYYOOsk..Ss",
    "....sk...rRRRRr....sk",
    ".Ss....WWw....wWW....Ss",
    "Ssk..cWWww....wwWWc..sk",
    ".sk..WwwwEeEEe.wwwW",
    "....Ss...EeE.eE....Ss",
    "...skk...Sss..Ss..skk",
    ".........kkk..skk",
  ],
  [
    "",
    "",
    "",
    "",
    "",
    "..........R",
    "..........RR..R",
    "..........RRR.R",
    ".........RRORRR",
    ".........ROOOR",
    "........RROOOORR",
    "........ROOYYOOR",
    "........ROYYYYOR",
    ".......RROYYYYOR",
    "........ROYYYYOSs",
    ".....Ss.ROOYYOOsk..Ss",
    "....sk...rRRRRr....sk",
    ".Ss....WWw....wWW....Ss",
    "Ssk..cWWww....wwWWc..sk",
    ".sk..WwwwEeEEe.wwwW",
    "....Ss...EeE.eE....Ss",
    "...skk...Sss..Ss..skk",
    ".........kkk..skk",
  ],
];

const FORGE_PAL = { "S": "#d4d8de", "M": "#a8aeb8", "D": "#7a808c", "K": "#555a64", "Y": "#fff6b0", "O": "#ffb03c", "R": "#ff6a2a", "r": "#a8301a", "N": "#c4cedc", "U": "#7a869c", "V": "#4a5268", "X": "#2e3446", "W": "#9a6438", "w": "#6a4020", "k": "#3a3a40" };
const FORGE = [
  [
    "..............SMMDK",
    "...............MMDK",
    "...............MMDK",
    "...............MMDK",
    "...............MMDK",
    "...............MMDK",
    "...............MMDK",
    "........SSMMMMMMMMDD",
    "......SSMMMMMMMMMMDD",
    ".....SMMMMMMMMMMMMDK",
    "....SSDMMMDMMMDMMMDK",
    "....SMMMMMMMMMMMMMDK",
    "...SSMKKKKKKKKKKMMDK",
    "...SMDKMMrrrrDMKMDDK",
    "...SMMKMrRRRRrMKMMDK",
    "...SMMKrROOOORrKMMDK",
    "...SMMKrROYYORrKMMDK",
    "...SMMKrOYYYYOrKMMDK",
    "...SMMKrOYYYYOrKMMDK",
    "...SDDDDDDDDDDDDDDKK",
    "....KKKKKKKKKKKKKKK",
    ".................NNNNNNNNNU",
    "...............NNNNNNNNNNVUV",
    "..................UUUUUVV.w",
    "...................VVVVX..w",
    "...................VVVX...W",
    ".................XVVVVVVX",
    ".................XXXXXXXX",
    "",
    "",
  ],
  [
    "..............SMMDK",
    "...............MMDK",
    "...............MMDK",
    "...............MMDK",
    "...............MMDK",
    "...............MMDK",
    "...............MMDK",
    "........SSMMMMMMMMDD",
    "......SSMMMMMMMMMMDD",
    ".....SMMMMMMMMMMMMDK",
    "....SSDMMMDMMMDMMMDK",
    "....SMMMMMMMMMMMMMDK",
    "...SSMKKKKKKKKKKMMDK",
    "...SMDKMMrrrrDMKMDDK",
    "...SMMKMrRRRRrMKMMDK",
    "...SMMKrRROORRrKMMDK",
    "...SMMKrROOYORrKMMDK",
    "...SMMKrOYYYOOrKMMDK",
    "...SMMKrOOYYYOrKMMDK",
    "...SDDDDDDDDDDDDDDKK",
    "....KKKKKKKKKKKKKKK",
    ".................NNNNNNNNNU",
    "...............NNNNNNNNNNVUV",
    "..................UUUUUVV.w",
    "...................VVVVX..w",
    "...................VVVX...W",
    ".................XVVVVVVX",
    ".................XXXXXXXX",
    "",
    "",
  ],
];

function paint(rows: string[], pal: Record<string, string>): HTMLCanvasElement {
  const w = Math.max(...rows.map(r => r.length));
  const p = new PixelCanvas(w, rows.length);
  rows.forEach((r, y) => [...r].forEach((ch, x) => ch !== '.' && pal[ch] && p.px(x, y, pal[ch])));
  return p.outline('auto', 0.35).toCanvas();
}

/** HD campfire: three frames of flame over crossed logs in a ring of stones. */
export function campfireFrames(): HTMLCanvasElement[] {
  return CAMPFIRE.map(f => paint(f, CAMP_PAL));
}

/** HD forge: a stone furnace with a chimney and an anvil; two frames of its glowing mouth. */
export function forgeFrames(): HTMLCanvasElement[] {
  return FORGE.map(f => paint(f, FORGE_PAL));
}

/** Chunky versions for the flat styles (drawn at 4×). */
export const FLAT_CAMPFIRE: string[][] = [["..R..", ".ROR.", ".ROYR", "wwOww", ".sws."], ["...R.", ".RRR.", "RROYR", "wwOww", ".sws."], [".R...", ".ROR.", ".RYOR", "wwOww", ".sws."]];
export const FLAT_FORGE: string[][] = [["....M.", ".MMMM.", "MMMMMD", "MMrRMD", "MMOYMD", "DDDDDD"], ["....M.", ".MMMM.", "MMMMMD", "MMRrMD", "MMYOMD", "DDDDDD"]];
export const FLAT_PAL: Pal = {"w": "#7a4e28", "Y": "#fff6b0", "O": "#ffb03c", "R": "#ff6a2a", "r": "#c8361c", "s": "#9a9a96", "M": "#a8a8a0", "D": "#787870"};
