import { PixelCanvas } from './pixelPainter';

/**
 * Menu bar, skill and talent icons: the skull (Execute), a sealed scroll (Quests), an iron
 * cog (Settings), a book (Controls), an eye, a flame, a heart and a star (Talents), and the
 * view button's map tile, turning block and camera. 20×20 with the HD outline. Generated by
 * tools/heroes (menuicons.py).
 */

const SKULL_PAL = { "L": "#f6eedc", "M": "#d6c9a8", "D": "#a08f6c", "K": "#2a1e26", "T": "#fffaf0", "r": "#e8443a" };
const SKULL = [
  "",
  "......LLLLLLM",
  "....LLLLLLLLLMM",
  "...LLLLLLLLLLLMM",
  "..LLLLLDLLLLLLMMM",
  "..LLLLLLDLLLLLMMD",
  "..LLLLLLDLLLLMMMD",
  "..LLKKKKLLLKKKKMD",
  "..LKKKKKLLKKKKKMD",
  "..LKKrKKLLKKrKKDD",
  "..LLKKKLLLLKKKMDD",
  "...LLLLLLKLLLMMD",
  "....LLLLKKKLMMD",
  "....MLLLLLLLMMD",
  ".....MTTTTTTMD",
  ".....DTDTDTDDD",
  ".....MTTTTTTMD",
  "......DDDDDDD",
  "",
  "",
];

const SCROLL_PAL = { "P": "#f4e2b8", "p": "#d8bc84", "q": "#a8885a", "l": "#9a7448", "R": "#e8443a", "r": "#a82424", "o": "#ff8a7a" };
const SCROLL = [
  "",
  "....pPPPPPPPPPPPq",
  "...pPPPPPPPPPPPPPq",
  "...qpppppppppppppq",
  "....PPPPPPPPPPPPp",
  "....PllllllllPPPp",
  "....PPPPPPPPPPPPp",
  "....PlllllllllPPp",
  "....PPPPPPPPPPPPp",
  "....PllllllPPPPPp",
  "....PPPPPPPPPPPPp",
  "....PlllllllPPPPp",
  "....PPPPPPPPPoRRp",
  "....PPPPPPPPoRRRr",
  "...pPPPPPPPPPRRrrq",
  "...pPPPPPPPPPPrrPq",
  "...qpppppppppppppq",
  "....qqqqqqqqqqqqq",
  "",
  "",
];

const COG_PAL = { "N": "#eef2f8", "O": "#c4cedc", "U": "#8c98b0", "V": "#5c6684", "X": "#3a4058" };
const COG = [
  "",
  ".........NN",
  ".........NN",
  "....N....NN....O",
  "...NNNNNNNNNOOOUU",
  "....NNNNNNNOOOUU",
  "....NNNNXXXXOUUU",
  "....NNNX....VUUU",
  "....NNX......VUV",
  ".NNNNNX......VVVVVV",
  ".NNNNNX......VVVVVV",
  "....NOX......VVV",
  "....OOOV....VVVV",
  "....OOUUVVVVVVVV",
  "....OUUUUVVVVVVV",
  "...OUUUUVVVVVVVVV",
  "....U....VV....V",
  ".........VV",
  ".........VV",
  "",
];

const BOOK_PAL = { "B": "#5a8ad8", "b": "#3a62b0", "k": "#24427e", "P": "#f4ead0", "p": "#c8b890", "G": "#ffe07a", "g": "#d8a03a" };
const BOOK = [
  "",
  "....bbbbbbbbbbbbk",
  "...BBBBBBBBBBBBbbk",
  "...BBBBBBBBBBBBbbk",
  "...BBBBBGGGGBBBbbk",
  "...BBBBGGBBGGBBbbk",
  "...BBBBBBBBGGBBbbk",
  "...BBBBBBBGGBBBbbk",
  "...BBBBBBGGBBBBbbk",
  "...BBBBBBGGBBBBbbk",
  "...BBBBBBBBBBBBbbk",
  "...BBBBBBGGBBBBbbk",
  "...BBBBBBggBBBBbbk",
  "...BBBBBBBBBBBBbbk",
  "...bbbbbbbbbbbbbbk",
  "...PPPPPPPPPPPPPpk",
  "...pppppppppppppkk",
  "....kkkkkkkkkkkkk",
  "",
  "",
];

const EYE_PAL = { "W": "#fffaf0", "w": "#d8d0c0", "I": "#5ac8f0", "i": "#2a7ab8", "K": "#1a1a26", "L": "#e8b890", "l": "#b07850", "G": "#ffe07a" };
const EYE = [
  "",
  "",
  "",
  "",
  "......llllllll",
  "....llLLLLLLLLll",
  "...lLLwwwwwwwwLLl",
  "..lLwwWWIIIIwwwLLl",
  ".lLwWWWIiiiIIwwwLl",
  ".lLwWWIiKKiiIwwwLl",
  ".lLwWWIiKKiiIwwwLl",
  ".lLwWWWIiiiIIwwwLl",
  "..lLwwWWIIIIwwwLLl",
  "...lLLwwwwwwwwLLl",
  "....llLLLLLLLLll",
  "......llllllll",
  "",
  "",
  "",
  "",
];

const FLAME_PAL = { "Y": "#fff6b0", "O": "#ffb03c", "R": "#ff6a2a", "r": "#c8361c", "q": "#8a2010" };
const FLAME = [
  "",
  ".........R",
  "........RR",
  "........RRR....R",
  ".......RROR...RR",
  "..R....ROORR..RR",
  "..RR..RROOOR.RRR",
  "..RRR.ROOOORRROR",
  "..RORRROOYOORROR",
  "..ROORROOYYOOROOR",
  "..ROOOOOYYYOOOOOR",
  ".RROOOOYYYYYOOOOR",
  ".ROOOOYYYYYYYOOORr",
  ".ROOOOYYYYYYYOOOOr",
  ".rROOOOYYYYYOOOORr",
  "..rROOOOYYYOOOORrr",
  "...rrRROOOOORRRrq",
  "....qrrrRRRRrrrq",
  "......qqqqqqqq",
  "",
];

const HEART_PAL = { "P": "#ffb0a8", "R": "#f0504a", "r": "#b82a2a", "q": "#7a1818", "W": "#ffffff" };
const HEART = [
  "",
  "",
  "",
  "...qqqq.....qqqq",
  "..qRRRRq...qRRRRq",
  ".qRPWRRRq.qRRRRrrq",
  ".qRWPRRRRqRRRRRrrq",
  ".qRPRRRRRRRRRRRrrq",
  ".qRRRRRRRRRRRRRrrq",
  "..qRRRRRRRRRRRrrq",
  "...qRRRRRRRRRrrq",
  "....qRRRRRRRrrq",
  ".....qRRRRRrrq",
  "......qRRRrrq",
  ".......qRrrq",
  "........qrq",
  ".........q",
  "",
  "",
  "",
];

const STAR_PAL = { "Y": "#fff6b0", "G": "#ffd84a", "g": "#d89a24", "b": "#9a5a10" };
const STAR = [
  "",
  ".........Y",
  ".........Y",
  ".........Y",
  "........YYY",
  "........YYG",
  ".......YYGGG",
  ".YYYYYYYGGGGGGGggg",
  "..YYYYYYYGGGGGggg",
  "...YYYGGGGGGGggg",
  ".....GGGGGGGgg",
  "......GGGGGgg",
  "......GGGGggg",
  ".....GGGGggggg",
  ".....GGGg.gggg",
  ".....GG.....gg",
  "....GG.......gg",
  "",
  "",
  "",
];

const SPELLBOOK_PAL = { "R": "#c84a4a", "r": "#902e2e", "q": "#5a1a1a", "G": "#ffe07a", "g": "#c8901e", "P": "#f4ead0", "p": "#c8b890" };
const SPELLBOOK = [
  "",
  "",
  "....qqqqqqqqqqqq",
  "...qRRRRRRRRRRRrq",
  "...qRgRRRRRRRRgrq",
  "...qRRRRRGGRRRRrq",
  "...qRRRRGRRGRRRrq",
  "...qRRRGRGGRGRRrq",
  "...qRRRGRGGRGRRrq",
  "...qRRRRGRRGRRRrq",
  "...qRRRRRGGRRRRrq",
  "...qRgRRRRRRRRgrq",
  "...qRRRRRRRRRRRrq",
  "...qrrrrrrrrrrrrq",
  "...qPPPPPPPPPPPPpq",
  "...qppppppppppppqq",
  "....qqqqqqqqqqqqq",
  "",
  "",
  "",
];

const VIEW_ISO_PAL = { "G": "#c8e494", "g": "#98c870", "h": "#72a256", "P": "#f2dcaa", "p": "#d0ae74", "L": "#b47e4c", "R": "#7c5438", "T": "#78bc5a", "U": "#4a8a40", "V": "#2e5e2e", "t": "#6a4428", "k": "#4e6a3a" };
const VIEW_ISO = [
  ".....TTT",
  "....TTTTU",
  "...TTTTUU",
  "...TTUUUV",
  "....UUtVVGG",
  "......tGGGGGh",
  ".....kkkGGhhhh",
  "....GGGGggggPPPp",
  "..GGGGggggPPPphhhh",
  ".LGGggggPPPpgggghhR",
  ".LLLggPPPpggggggRRR",
  ".LLLLPPpggggggRRRRR",
  "..LLLLLggggggRRRRR",
  "....LLLLLggRRRRR",
  ".....LLLLLRRRR",
  ".......LLLRRR",
  ".........LR",
  "",
  "",
  "",
];

const VIEW_3D_PAL = { "G": "#c8e494", "g": "#98c870", "h": "#72a256", "k": "#4e7a3e", "L": "#c08a56", "l": "#a4703e", "R": "#7c5438", "r": "#64422c", "T": "#78bc5a", "U": "#4a8a40", "V": "#2e5e2e", "t": "#6a4428", "A": "#ffe48a", "a": "#e8b038", "b": "#a87020" };
const VIEW_3D = [
  "",
  "",
  ".......TTU",
  "......TTTUU",
  "......TTUUV",
  ".......UVVGhh",
  ".....GGGtggghhh",
  "...GGGGgtkgggghhh",
  "...hhggggggggggkk",
  "...LLhhggggggkkRR",
  "...LLLLhhggkkRRRR",
  "...LLLLLLhkRRRRRR",
  "...LLllLLLRRRRRRR",
  "a..LLLLLLLRRRrrRR",
  "aa...LLLlLRRRRR",
  "baa....LLLRRr.A",
  ".baaa....LR...AAA",
  "..bbaaaaaaaaaaaAAAA",
  "....bbbbbbbbbbaAAb",
  "..............ab",
];

const VIEW_POV_PAL = { "K": "#4e4856", "k": "#2e2834", "S": "#eef2f8", "s": "#aab2c4", "m": "#7a8296", "L": "#16141e", "B": "#4a7ad0", "b": "#2a4a90", "H": "#cfe8ff", "R": "#f0483c" };
const VIEW_POV = [
  "",
  "",
  "",
  "..sss......sssss",
  ".sSSSs....sSSSSSs",
  "sSSSSSSSSSSSSSSSSsm",
  "KKKKKKKmmmmmKKKKKKk",
  "KKKKKKmLLLLLmKKRKKk",
  "KKKKKmLbbbbbLmKKKKk",
  "KKKKmLbbHHbbbLmKKKk",
  "KKKKmLbbHBbbbLmKKKk",
  "KKKKmLbbbbbbbLmKKKk",
  "KKKKmLbbbbbbbLmKKKk",
  "KKKKKmLbbbbbLmKKKKk",
  "KKKKKKmLLLLLmKKKKKk",
  "kkkkkkkmmmmmkkkkkkk",
  "",
  "",
  "",
  "",
];

function paint(rows: string[], pal: Record<string, string>): HTMLCanvasElement {
  const w = Math.max(...rows.map(r => r.length));
  const p = new PixelCanvas(w, rows.length);
  rows.forEach((r, y) => [...r].forEach((ch, x) => ch !== '.' && pal[ch] && p.px(x, y, pal[ch])));
  return p.outline('auto', 0.3).toCanvas();
}


export const skullIcon = (): HTMLCanvasElement => paint(SKULL, SKULL_PAL);
export const scrollIcon = (): HTMLCanvasElement => paint(SCROLL, SCROLL_PAL);
export const cogIcon = (): HTMLCanvasElement => paint(COG, COG_PAL);
export const bookIcon = (): HTMLCanvasElement => paint(BOOK, BOOK_PAL);
export const eyeIcon = (): HTMLCanvasElement => paint(EYE, EYE_PAL);
export const flameIcon = (): HTMLCanvasElement => paint(FLAME, FLAME_PAL);
export const heartIcon = (): HTMLCanvasElement => paint(HEART, HEART_PAL);
export const starIcon = (): HTMLCanvasElement => paint(STAR, STAR_PAL);
export const spellbookIcon = (): HTMLCanvasElement => paint(SPELLBOOK, SPELLBOOK_PAL);
export const view_isoIcon = (): HTMLCanvasElement => paint(VIEW_ISO, VIEW_ISO_PAL);
export const view_3dIcon = (): HTMLCanvasElement => paint(VIEW_3D, VIEW_3D_PAL);
export const view_povIcon = (): HTMLCanvasElement => paint(VIEW_POV, VIEW_POV_PAL);
